[package]
name = "deepfilter-vst"
version = "0.5.0"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["cdylib", "lib"]

[features]
default = ["model-ll"]
model-ll = ["df/default-model-ll"]
model-standard = ["df/default-model"]

[dependencies]
nice-plug = "=0.2.3"

df = { git = "https://github.com/Rikorose/DeepFilterNet.git", tag = "v0.5.6", package = "deep_filter", default-features = false, features = ["tract"] }

ndarray = "0.15"
log = "0.4"
rubato = "=0.14.1"
rtrb = "=0.3.3"
